# Generated by Django 3.0.5 on 2021-05-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courseid',
        ),
    ]
