# Generated by Django 3.0.5 on 2021-05-13 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_courses_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='handoutfilename',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
