# Generated by Django 3.0.5 on 2021-05-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_courses_handoutfilename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
