# Generated by Django 3.0.5 on 2021-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_registered_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('courseid', models.CharField(max_length=10)),
                ('status', models.CharField(default='Not Registered', max_length=20)),
            ],
        ),
    ]
