# Generated by Django 3.0.5 on 2021-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_student_registered_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_registered_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=20)),
                ('credits', models.CharField(max_length=10)),
                ('handoutfilename', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='student_registered_courses',
            name='status',
            field=models.CharField(default='Click to Register', max_length=20),
        ),
    ]
