# Generated by Django 3.0.5 on 2021-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20210513_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.CharField(default='NA', max_length=100)),
                ('book_name', models.CharField(default='NA', max_length=50)),
                ('book_author', models.CharField(default='NA', max_length=50)),
                ('book_pub_date', models.CharField(default='NA', max_length=20)),
                ('book_desc', models.TextField(default='NA', max_length=255)),
                ('book_tag1', models.CharField(default='NA', max_length=20)),
                ('book_tag2', models.CharField(default='NA', max_length=20)),
                ('book_tag3', models.CharField(default='NA', max_length=20)),
                ('book_tag4', models.CharField(default='NA', max_length=20)),
                ('book_pic', models.ImageField(blank=True, default='book.jpg', null=True, upload_to='')),
                ('book_file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
