# Generated by Django 3.0.5 on 2021-05-19 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20210518_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_result',
            name='attempted_date',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 11, 0, 55, 298908)),
        ),
    ]
