# Generated by Django 3.0.5 on 2021-05-19 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20210519_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendsms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 11, 49, 23, 935486)),
        ),
    ]
