# Generated by Django 3.0.5 on 2021-05-19 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20210519_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_time',
            field=models.TimeField(default=datetime.datetime(2021, 5, 19, 12, 1, 12, 769529)),
        ),
    ]
