# Generated by Django 3.2.7 on 2021-09-16 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20210519_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_date',
            field=models.DateField(default=datetime.date(2021, 9, 16)),
        ),
        migrations.AlterField(
            model_name='quiz_result',
            name='attempted_time',
            field=models.TimeField(default=datetime.datetime(2021, 9, 16, 10, 12, 41, 230492)),
        ),
    ]
